
version: 2.1


jobs:
  my-jop:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: return 1
      - run: |
          when: on_fail
          echo "hello error"
          



workflows:
  welcome:
    jobs:
      - my-jop
      