
version: 2.1

jobs:
  save_hello_world_output:

    docker:
      - image: circleci/node:13.8.0

    steps:
      - checkout
      - run:
          name: "mario"
          command:
            echo "hello world" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_output_file:

    docker:
      - image: circleci/node:13.8.0

    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: "mafdy"
          command:
            cat ~/output.txt


workflows:
  welcome:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
      